name: format

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          ./scripts/format

  format-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - run: bun x prettier --check "**/*.{js,jsx,ts,tsx,json,md,yaml,yml}"
